### ISSUE TITLE
[FEATURE REQUEST] Publishing lwt-pipe in OPAM

### ISSUE THREAD

**Issue by pdonadeo** [c-cube/lwt-pipe#14]
I'm opening this "issue" only to ask... why aren't you publishing lwt-pipe? In my opinion it's a very useful library, with also a mention in the official documentation of Lwt.

It definitely deserve to be a first class citizen in the OCaml ecosystem.

**Comment by c-cube** [comment]
you're right, I shouldn't let this in limbo forever.
Here's version 0.1, comes with no guarantee :)
https://github.com/ocaml/opam-repository/pull/15742
