### ISSUE TITLE
Intended behavior when creating pipe's from Lwt_io's channels

### ISSUE THREAD

**Issue by anuragsoni** [c-cube/lwt-pipe#15]
This is more of a question about the intended behavior when creating pipes from Lwt's channels.
One usecase that I had in mind was to use `connect` to shuttle content between an input and output channel. A simplified version can be seen in the following snippet for an echo server. 

```ocaml
module Pipe = Lwt_pipe
Lwt_io.establish_server_with_client_address listen_address (fun _ (ic, oc) ->
    let reader = Pipe.IO.read ic in
    let writer = Pipe.IO.write oc in
    Lwt_pipe.connect ~ownership:`OutOwnsIn reader writer;
    Pipe.wait writer)
```
When using connect it is clear that using `ownsership`' we can control  which pipes owns the other, and that when the owner is closed, the ownee will also be closed. But when creating pipes via a channel its not clear to me when to close the owner pipe. `connect` returns unit so i can't wait on a promise that resolves when all the content has been transferred from owner to ownee. Without that if i can't close the reader pipe, then the writer pipe will also remain open and in my example above the promise in the server handle will never be resolved.

I'm not very familiar with Lwt's channels yet, but should the reader pipe created from an input_channel automatically close when all content from the channel has been consumed? (whenever the channel encounters EOF)

**Comment by c-cube** [comment]
It would make sense to have a `connect_and_wait` I imagine. RIght now, reading the code (from a few years ago) it seems that when the reader thread terminates, it closes the Reader pipe, which should then close the writer pipe by ownership if it were the reader owning the writer?

It might very well be that I didn't think of this use case.

**Comment by anuragsoni** [comment]
Hmm, I should have checked the implementation, looking at the code it does look like it should close the reader pipe. I need to spend more time on this, but as a first attempt when i tried to add some logs to trace the `read` call, i see `send ()` run once, but during the next call to `send ()` at https://github.com/c-cube/lwt-pipe/blob/d7b7ff45153eb9ea4d693328e79c1742fcc28052/src/Lwt_pipe.ml#L701-L703 the bind's not resolved and things look stuck. I need to go through `Lwt_io` but maybe this is just user error on my part afterall :)

**Comment by anuragsoni** [comment]
I feel dumb. This was definitely user error. I guess `nc` doesn't exit after receving EOF?
`echo "hello world" | nc 127.0.0.1 8080` was what i felt was the server getting stuck.

Doing the same with `echo "hello world" | socat - TCP:127.0.0.1:8080` works as expected and the pipe gets closed.

Sorry for the noise!
