### ISSUE TITLE
Passing rw pipe into reader combinator methods

### ISSUE THREAD

**Issue by Lupus** [c-cube/lwt-pipe#9]
I'm trying to use this library for creating communication channel between Lwt "threads", as it's recommended in Lwt documentation, but can't figure it out (disclaimer: ocaml newbie here).

I'm trying to create an `[r|w]` pipe, use it in producer and consumer. According to the docs it should be possible, but `Lwt_pipe.Reader.iter` expects `[r]` permissions and when I try to pass `[r|w]` pipe into `Lwt_pipe.Reader.iter` I get the following error:

```
# Error: This expression has type (item, [ `r | `w ]) Lwt_pipe.t
#        but an expression was expected of type
#          item Lwt_pipe.Reader.t = (item, [ `r ]) Lwt_pipe.t
#        The second variant type does not allow tag(s) `w
```

I tried fiddling with coercion but no luck. Usage example in readme creates `Lwt_pipe.Reader.t` using `of_list` which is not exactly what I'm trying to do. Any help is greatly appreciated!

**Comment by c-cube** [comment]
It's a shortcoming of the API, it seems. Most of the functions in `Lwt_pipe.Reader` take a `('a, [>`r]) pipe` (which would work in your case) but not the `iter` functions.

You can try to make a PR (it's just about changing the type signatures) or wait for me to do it, whatever you prefer :)

**Comment by Lupus** [comment]
Something along these lines? At least it compiled fine now, i'll test it later and if everything works can make a PR on this (if you don't apply this patch yourself earlier :-p ).

```diff
-  val iter : f:('a -> unit) -> 'a t -> unit Lwt.t
+  val iter : f:('a -> unit) -> ('a, [>`r]) pipe -> unit Lwt.t
 
-  val iter_s : f:('a -> unit Lwt.t) -> 'a t -> unit Lwt.t
+  val iter_s : f:('a -> unit Lwt.t) -> ('a, [>`r]) pipe -> unit Lwt.t
 
-  val iter_p : f:('a -> unit Lwt.t) -> 'a t -> unit Lwt.t
+  val iter_p : f:('a -> unit Lwt.t) -> ('a, [>`r]) pipe -> unit Lwt.t
```

Btw, how can one get strictly read or write ends of the `[r|w]` pipe? There should probably be some split function `('a, [< r | w ]) pipe -> ('a, [ r ]) pipe * ('a, [ w ]) pipe` (backticks in polymorphic variants omitted due to github formatting) to create strictly read only and write only references.

**Comment by c-cube** [comment]
Yes, something like that (also for the other remaining functions). The `split` function seems a bit unecessary if the API is fixed, since a full r/w pipe can act both as read and write ends, but it wouldn't hurt (or at least `reader: [>r] pipe -> [r] pipe`, and similarly for writer).

**Comment by Lupus** [comment]
I though the whole idea to have separate tags for readers and writers was to have separated instances, so that you can pass read end where you don't expect any writes (and vice versa for write end). Type system will guarantee that your expectations hold true, which is nice :)

```ocaml
val reader: [>`r] pipe -> [`r] pipe
val writer: [>`w] pipe -> [`w] pipe
```

This sounds nice! But I'm not sure how to implement that :)

**Comment by c-cube** [comment]
Internally it's implemented by identity :)

Readers and writers are separate because some combinators take pipe with read capabilities and return new readers (which are purely readers).

**Comment by Lupus** [comment]
Thanks! :)
